name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install sshpass on the runner
    - name: Install SSH client
      run: sudo apt-get install -y sshpass

    # Use sshpass to log in and run docker-compose commands on the server
    - name: Deploy via SSH
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 6262 server@115.187.22.70 <<EOF
          cd /home/server/text-analyzer-challenge
          sudo git pull origin main
          sudo docker stop text-analyzer-challenge
          sudo docker remove text-analyzer-challenge
          sudo docker rmi text-analyzer-challenge
          sudo docker build -t text-analyzer-challenge .
          sudo docker-compose up -d
        EOF